// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To update this file, edit the 'hosting' section in your 'firebase.json' file and run 'firebase apphosting:sdkconfig'
// For more information, see https://firebase.google.com/docs/app-hosting/manage-backends#sdk-config

import { FirebaseOptions } from 'firebase/app';

let firebaseConfig: FirebaseOptions | undefined;

// This is a placeholder for the Firebase configuration.
// In a real environment, this would be populated by the App Hosting SDK.
if (process.env.NEXT_PUBLIC_FIREBASE_CONFIG) {
  try {
    firebaseConfig = JSON.parse(process.env.NEXT_PUBLIC_FIREBASE_CONFIG);
  } catch (e) {
    console.error("Failed to parse NEXT_PUBLIC_FIREBASE_CONFIG", e);
  }
} else {
    firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };
}


export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig) {
    throw new Error(
      'Firebase configuration not found. Make sure the environment is set up correctly.'
    );
  }
  return firebaseConfig;
}
